### ISSUE TITLE
Updates ?

### ISSUE THREAD

**Issue by extremeshok** [thynan/blesta-ispconfig#1]
I know you guys use a private gitlab to manage this project.

Do you have any updates which can be commited to this repo ?

thanks

**Comment by thynan** [comment]
Hi!
No, we don't have any updates yet. The module works for our (rather restricted) use at the moment, so we won't continue developing it until the new "domain management" is released with blesta core. When that happens, we plan to upgrade and extend this module. As far as I know, that  will happen with Blesta 4.1 (fingers crossed).

**Comment by shadyo62** [comment]
Hello, I have an error when I add a server with the ispconfig module :

The SessionID is empty. on line 85 in /var/www/clients/client0/web1/web/espaceclient/components/modules/ispconfig/apis/ispconfig_api.php 

Printing Stack Trace:
#0 /var/www/clients/client0/web1/web/espaceclient/components/modules/ispconfig/apis/ispconfig_api.php(85): SoapClient->__call('logout', Array)
#1 /var/www/clients/client0/web1/web/espaceclient/components/modules/ispconfig/apis/ispconfig_api.php(85): SoapClient->logout(NULL)
#2 [internal function]: IspconfigApi->__destruct()
#3 [internal function]: Ispconfig->validateConnection('****', '****', '*****', '******', '*****')
#4 /var/www/clients/client0/web1/web/espaceclient/components/input/input.php(478): call_user_func_array(Array, Array)
#5 /var/www/clients/client0/web1/web/espaceclient/components/input/input.php(317): Input->validateRule('remote_pw', Array, '*******', 'remote_pw')
#6 /var/www/clients/client0/web1/web/espaceclient/components/modules/ispconfig/ispconfig.php(451): Input->validates(Array)
#7 /var/www/clients/client0/web1/web/espaceclient/app/models/module_manager.php(474): Ispconfig->addModuleRow(Array)
#8 /var/www/clients/client0/web1/web/espaceclient/app/controllers/admin_company_modules.php(291): ModuleManager->addRow('1', Array)
#9 /var/www/clients/client0/web1/web/espaceclient/lib/dispatcher.php(111): AdminCompanyModules->addRow()
#10 /var/www/clients/client0/web1/web/espaceclient/index.php(21): Dispatcher::dispatch('/espaceclient/a...')
#11 {main}

Can help me?
Thanks
